import fs from 'node:fs'
const src = 'D:/FireflyQAQ/Project/FrontProj/line-art-style-magic-cabin-main/index.html'
const text = fs.readFileSync(src, 'utf8')
const lines = text.split(/\r?\n/)
console.log('总行数:', lines.length)
console.log('字符数:', text.length)
const find = (re) => lines.map((l,i)=>[i+1,l]).filter(([,l])=>re.test(l)).map(([n])=>n)
console.log('<style>:', find(/^\s*<style>\s*$/))
console.log('</style>:', find(/^\s*<\/style>\s*$/))
console.log('<body>:', find(/^\s*<body>\s*$/))
console.log('</body>:', find(/^\s*<\/body>\s*$/))
console.log('<script ...>:', find(/<script[^>]*>/))
console.log('</script>:', find(/^\s*<\/script>\s*$/))
console.log('--- 前 12 行 ---')
lines.slice(0,12).forEach((l,i)=>console.log(String(i+1).padStart(5)+'| '+l))
console.log('--- 745..755 ---')
lines.slice(744,755).forEach((l,i)=>console.log(String(i+745).padStart(5)+'| '+l))
console.log('--- 833..846 ---')
lines.slice(832,846).forEach((l,i)=>console.log(String(i+833).padStart(5)+'| '+l))
console.log('--- 尾部 9795..' + lines.length + ' ---')
lines.slice(9794).forEach((l,i)=>console.log(String(i+9795).padStart(5)+'| '+JSON.stringify(l)))
